### ISSUE TITLE
Pages not accessible for non-registered users

### ISSUE THREAD

**Issue by bd8670** [FriendsOfFlarum/pages#30] opened 2021-02-21 19:28 UTC
My flarum-forum can only be viewed by registered users.
Wanted non-registered users to be able to view 2 specific pages using the pages-extension, but pages cannot be viewed by non-registered users.
How could I fix this please?
Thanks

**Comment by clarkwinkelmann** [comment] 2021-02-22 17:31
All pages not marked "restricted" and which are no longer drafts should be visible by everyone including guests.

Pages marked "restricted" should follow the permission for restricted pages.

Can you share the output of `php flarum info`, and a screenshot of the Permissions page (so we can see everything under Read category including "View discussions" and "View restricted pages")

**Comment by clarkwinkelmann** [comment] 2021-04-04 23:34
Closing this issue because we don't have enough information to reproduce. If you are still experiencing this please reply with additional details and we'll re-open.

**Closed as completed by clarkwinkelmann** 2021-04-04 23:34 UTC
