### ISSUE TITLE
v0.5.0 errors

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/pages#27] opened 2020-11-06 20:37 UTC
There are 2 critical errors. I created the page but it did not appear in the page list. It seemed that I have refreshed the page. I tried opening the page, the link was broken.

```
[2020-11-06 20:32:44] flarum.ERROR: InvalidArgumentException: No hint path defined for [fof-pages]. in /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php:112
Stack trace:
#0 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments()
#1 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView()
#2 /var/www/html/flarum/vendor/illuminate/view/Factory.php(131): Illuminate\View\FileViewFinder->find()
#3 /var/www/html/flarum/vendor/fof/pages/src/Content/Page.php(71): Illuminate\View\Factory->make()
#4 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Frontend.php(63): FoF\Pages\Content\Page->__invoke()
#5 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Frontend.php(55): Flarum\Frontend\Frontend->populate()
#6 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#7 /var/www/html/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Frontend\Controller->handle()
#8 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#9 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#10 /var/www/html/flarum/vendor/fof/ban-ips/src/Middleware/RegisterMiddleware.php(93): Laminas\Stratigility\Next->handle()
#11 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\BanIPs\Middleware\RegisterMiddleware->process()
#12 /var/www/html/flarum/vendor/fof/stopforumspam/src/Middleware/RegisterMiddleware.php(101): Laminas\Stratigility\Next->handle()
#13 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\StopForumSpam\Middleware\RegisterMiddleware->process()
#14 /var/www/html/flarum/vendor/fof/terms/src/Middlewares/RegisterMiddleware.php(48): Laminas\Stratigility\Next->handle()
#15 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\Terms\Middlewares\RegisterMiddleware->process()
#16 /var/www/html/flarum/vendor/fof/oauth/src/Middleware/ErrorHandler.php(50): Laminas\Stratigility\Next->handle()
#17 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\OAuth\Middleware\ErrorHandler->process()
#18 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#19 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#20 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#21 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#22 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(37): Laminas\Stratigility\Next->handle()
#23 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#24 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#25 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#26 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#27 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#28 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#29 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#30 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#31 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CollectGarbage->process()
#32 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#33 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#34 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#35 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#36 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#37 /var/www/html/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#38 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#39 /var/www/html/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#40 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#41 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#42 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#43 /var/www/html/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#44 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#45 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#46 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#47 /var/www/html/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#48 /var/www/html/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#49 /var/www/html/flarum/index.php(26): Flarum\Http\Server->listen()
#50 {main}


[2020-11-06 11:12:39] flarum.ERROR: Exception: Serialization of 'Closure' is not allowed in /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php:120
Stack trace:
#0 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(120): serialize()
#1 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(117): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#2 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(117): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#3 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(117): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#4 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(117): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#5 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(117): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#6 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/Helpers/ConfigHelper.php(117): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#7 /var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator.php(257): s9e\TextFormatter\Configurator\Helpers\ConfigHelper::optimizeArray()
#8 /var/www/html/flarum/vendor/flarum/core/src/Formatter/Formatter.php(156): s9e\TextFormatter\Configurator->finalize()
#9 /var/www/html/flarum/vendor/illuminate/cache/Repository.php(418): Flarum\Formatter\Formatter->Flarum\Formatter\{closure}()
#10 /var/www/html/flarum/vendor/flarum/core/src/Formatter/Formatter.php(157): Illuminate\Cache\Repository->rememberForever()
#11 /var/www/html/flarum/vendor/flarum/core/src/Formatter/Formatter.php(200): Flarum\Formatter\Formatter->getComponent()
#12 /var/www/html/flarum/vendor/flarum/core/src/Forum/ForumServiceProvider.php(100): Flarum\Formatter\Formatter->getJs()
#13 [internal function]: Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#14 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Compiler/Source/StringSource.php(35): call_user_func()
#15 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Compiler/Source/StringSource.php(46): Flarum\Frontend\Compiler\Source\StringSource->getContent()
#16 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(239): Flarum\Frontend\Compiler\Source\StringSource->getCacheDifferentiator()
#17 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(73): Flarum\Frontend\Compiler\RevisionCompiler->calculateRevision()
#18 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(125): Flarum\Frontend\Compiler\RevisionCompiler->commit()
#19 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Content/Assets.php(73): Flarum\Frontend\Compiler\RevisionCompiler->getUrl()
#20 [internal function]: Flarum\Frontend\Content\Assets->Flarum\Frontend\Content\{closure}()
#21 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Content/Assets.php(72): array_map()
#22 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Content/Assets.php(55): Flarum\Frontend\Content\Assets->getUrls()
#23 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Frontend.php(63): Flarum\Frontend\Content\Assets->__invoke()
#24 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Frontend.php(55): Flarum\Frontend\Frontend->populate()
#25 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#26 /var/www/html/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Frontend\Controller->handle()
#27 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#28 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#29 /var/www/html/flarum/vendor/fof/secure-https/src/Middlewares/ContentSecurityPolicyMiddleware.php(32): Laminas\Stratigility\Next->handle()
#30 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\SecureHttps\Middlewares\ContentSecurityPolicyMiddleware->process()
#31 /var/www/html/flarum/vendor/fof/ban-ips/src/Middleware/RegisterMiddleware.php(93): Laminas\Stratigility\Next->handle()
#32 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\BanIPs\Middleware\RegisterMiddleware->process()
#33 /var/www/html/flarum/vendor/fof/stopforumspam/src/Middleware/RegisterMiddleware.php(101): Laminas\Stratigility\Next->handle()
#34 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\StopForumSpam\Middleware\RegisterMiddleware->process()
#35 /var/www/html/flarum/vendor/fof/terms/src/Middlewares/RegisterMiddleware.php(48): Laminas\Stratigility\Next->handle()
#36 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\Terms\Middlewares\RegisterMiddleware->process()
#37 /var/www/html/flarum/vendor/fof/oauth/src/Middleware/ErrorHandler.php(50): Laminas\Stratigility\Next->handle()
#38 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\OAuth\Middleware\ErrorHandler->process()
#39 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#40 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#41 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#42 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#43 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(37): Laminas\Stratigility\Next->handle()
#44 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#45 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#46 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#47 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#48 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#49 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#50 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#51 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#52 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CollectGarbage->process()
#53 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#54 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#55 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#56 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#57 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#58 /var/www/html/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#59 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#60 /var/www/html/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#61 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#62 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#63 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#64 /var/www/html/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#65 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#66 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#67 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#68 /var/www/html/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#69 /var/www/html/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#70 /var/www/html/flarum/index.php(26): Flarum\Http\Server->listen()
#71 {main} 
```

**Comment by karaok491** [comment] 2020-11-06 21:55
I can replicate the non-refresh issue, so will get that looked at. However the main issue I cannot. Please provide more information to replicate

**Comment by clarkwinkelmann** [comment] 2020-11-07 00:21
Can you try running `php flarum cache:clear` if not already done?

If the error still happens, can you share the output of `php flarum info`?

If it's not a cache issue, I think that first backtrace could be caused by having another extension installed which is improperly registering its views.

**Comment by ghost** [comment] 2020-11-07 02:05
I accidentally closed the issue. I re-opened. the extension is currently disabled.
php flarum info
```
Flarum core 0.1.0-beta.14.1
PHP version: 7.4.12
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip
+---------------------------------+------------------+--------+
| Flarum Extensions               |                  |        |
+---------------------------------+------------------+--------+
| ID                              | Version          | Commit |
+---------------------------------+------------------+--------+
| flarum-approval                 | v0.1.0-beta.14   |        |
| flarum-bbcode                   | v0.1.0-beta.12   |        |
| flarum-emoji                    | v0.1.0-beta.14   |        |
| flarum-flags                    | v0.1.0-beta.14.1 |        |
| flarum-likes                    | v0.1.0-beta.14   |        |
| flarum-lock                     | v0.1.0-beta.14   |        |
| flarum-markdown                 | v0.1.0-beta.14   |        |
| flarum-mentions                 | v0.1.0-beta.14   |        |
| flarum-sticky                   | v0.1.0-beta.14   |        |
| flarum-subscriptions            | v0.1.0-beta.14   |        |
| flarum-suspend                  | v0.1.0-beta.14   |        |
| flarum-tags                     | v0.1.0-beta.14   |        |
| flarum-lang-english             | v0.1.0-beta.14.1 |        |
| flarum-statistics               | v0.1.0-beta.14   |        |
| fof-user-bio                    | 0.3.1            |        |
| tolgaaaltas-lang-turkish        | 0.14.1           |        |
| askvortsov-moderator-warnings   | v0.3.0           |        |
| v17development-seo              | 1.4              |        |
| fof-follow-tags                 | 0.5.0            |        |
| fof-formatting                  | 0.2.0            |        |
| fof-split                       | 0.5.0            |        |
| tolgaaaltas-turkish             | 0.14.0           |        |
| nearata-signup-confirm-password | v2.1.0           |        |
| fof-forum-statistics-widget     | 0.3.0            |        |
| nearata-copy-code-to-clipboard  | v1.1.0           |        |
| fof-drafts                      | 0.2.0            |        |
| fof-best-answer                 | 0.2.0            |        |
| fof-links                       | 0.4.0            |        |
| fof-linguist                    | 0.4.4            |        |
| fof-oauth                       | 0.1.0            |        |
| fof-terms                       | 0.5.0            |        |
| fof-merge-discussions           | 0.4.0            |        |
| fof-spamblock                   | 0.3.0            |        |
| fof-stopforumspam               | 0.3.1            |        |
| fof-geoip                       | 0.2.0            |        |
| fof-ban-ips                     | 0.3.0            |        |
| matteocontrini-imgur-upload     | v3.4.1           |        |
| fof-reactions                   | 0.4.2            |        |
+---------------------------------+------------------+--------+
Base URL: https://dursuncanpoyraz.com.tr/flarum
Installation path: /var/www/html/flarum
Debug mode: off
```

**Comment by northeaster** [comment] 2020-11-07 02:05
.

**Comment by northeaster** [comment] 2020-11-07 02:05
.

**Comment by karaok491** [comment] 2020-11-07 13:56
Disable `askvortsov-moderator-warnings` - I belive this to be the cause of the view related issue

https://github.com/askvortsov1/flarum-moderator-warnings/blob/5bf2341d3b42c33f98fcca11b663dc0da7fb1901/extend.php#L54 - this is registering it's views incorrectly for beta 14

**Comment by ghost** [comment] 2020-11-07 14:00
https://dursuncanpoyraz.com.tr/flarum/p/2-hakkimda **solved**. Do you report the extension [askvortsov1/flarum-moderator-warnings](https://github.com/askvortsov1/flarum-moderator-warnings) ?

**Comment by karaok491** [comment] 2020-11-07 14:04
Great. I've let @askvortsov1 know via discord, but I guess it wouldn't hurt to open an issue on https://github.com/askvortsov1/flarum-moderator-warnings

I will close this issue now, as it's not related to this extension

**Closed as completed by karaok491** 2020-11-07 14:04 UTC
